### ISSUE TITLE
Why are Boolean values saved as Strings in Dynamo?

### ISSUE THREAD

**Issue by glidester** [mingchuno/aws-wrap#10]
I've just noticed that the implicit conversion of Boolean values to an AttributeValue uses the 'withS' method rather than the 'withBOOL' method. This results in the Boolean value being persisted as a String in the Dynamo table. 

From dynamodb/package.scala
`  /** Boolean to a string AttributeValue */
  implicit val booleanToAttributeValue = (x: Boolean) => new AttributeValue().withS(x.toString)`

Is there some fundamental reason for this or just an oversight?

Thanks

Tim

**Comment by mingchuno** [comment]
I forked this proj from `dwhjames/aws-wrap` . I agree `withBOOL` is more reasonable. How about the `booleanIterableToAttributeValue`? If we have come to an agreement, can you submit a PR with test included?

**Comment by glidester** [comment]
I posted this on your fork as you seem a lot more active than the root project atm :)

I'd be happy to do a PR, just a little concerned though that if I altered the 'booleanToAttributeValue' and 'booleanIterableToAttributeValue' methods it might break code that others have written against the library (though I'm not sure there is a better alternative).

**Comment by mingchuno** [comment]
Yes, of coz we would break the compatibility. Since it is an `implicit val` in the scope, we cannot do the standard deprecation steps.  ;(

Interesting that the `attributeValueToBoolean ` is calling `x.getBOOL`.... So we would may things more reasonable by doing this? Anyway, If we are doing this, we must update the version and add note in README

**Comment by glidester2** [comment]
Hi mingchuno, hit a snag. Looks like there is no way for me to change the origin of my fork from 'dwhjames/aws-wrap' to 'mingchuno/aws-wrap' without deleting it completely :(

I've had to create this other account to be able to create a new fork. Just so you know its me when you get the pull request.

Tim

**Comment by mingchuno** [comment]
@glidester @glidester2 You can use `git add remote <some_name> git@github.com:mingchuno/aws-wrap.git` in your fork to sync my master branch. Then you can push your change to a new branch under your name. Finally you can open a PR from your feature branch against my master.

**Comment by glidester** [comment]
Thanks for tip regarding Git.

However, trying to do the proposed change correctly I've come to the conclusion that there needs to be a far greater change to the datatype implicit conversion code.

Investigating the `booleanIterableToAttributeValue` I've come to understand that there was a change in the available dataTypes between DynamoDb Schemas v1 and v2:

[dynamodb-series-conversion-schemas](https://aws.amazon.com/blogs/developer/dynamodb-series-conversion-schemas/)

Consulting the documentation:

[API_AttributeValue](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html)

It appears that in v1 Booleans where stored as `N` (0=false, 1=true) and as you could store Sets of Numbers you could also store Sets of Booleans. In v2 however Boolean values are stored as `BOOL` instead of `N`, there is no facility to store Sets of `BOOL`. Instead with v2 we can store a` L` of `BOOL`

This leads me to the reason why I think we need a wider change in the implicit conversion code.

In the DynamoDb Schemas v1 the only collection type was Set, but in v2 we have Set, List and Hash.

In the current implicit conversion code (com.github.dwhjames.awswrap.dynamodb.package) we have implicit functions such as:

`stringIterableToAttributeValue = (x: Iterable[String]) => new AttributeValue().withSS(x.asJavaCollection)`

This will convert a scala.collection `Set` and `Seq` of strings to a DynamoDb `SS` with no option of control. I think if I had a `Seq[String]` I would prefer to have a Dynamo L of strings rather than a SS as I might loose the order and dupe values of my sequence.

I propose creating a new set of conversion functions such as:

`stringSetToAttributeValue = (x: Set[String]) => new AttributeValue().withSS(x.asJavaCollection)
stringSeqToAttributeValue = (x: Seq[String]) => new AttributeValue().withL(x.map( stringToAttributeValue(_) ).asJavaCollection)`

To avoid breaking existing code I propose creating a new companion object that can be imported by the user instead of the current `com.github.dwhjames.awswrap.dynamodb.package`

Not sure how long it will take me to complete but please let me know if you have any thoughts/questions about my proposal.

Thanks,

Tim

**Comment by mingchuno** [comment]
Thank you for your investigation. I agree with your approach. If I understand correctly:
1. Is the current code compatible with DynamoDB V1 schema? (I think so?)
2. And if a client using DynamoDB V2 schema, it will suffer problem as you said? (like storing `Boolean` as `S` but not `BOOL` and `Seq[String]` as `SS` but not `LS``)

However, I saw the `package object dynamodb` contains type def from `com.amazonaws.services.dynamodbv2.model.AttributeValue`? And `attributeValueToX` seems using `BOOL` instaed of `L` or `S`? But still, we can definitely try to impl in a new package like `com.github.dwhjames.awswrap.dynamodb.v2`. Any other file in the original package is affected? We can reuse all other code?

**Comment by glidester** [comment]
Yes I think the current code is designed for the v1 data type Schema although looking through the git history it seems `package.scala` has always been written against the `com.amazonaws.services.dynamodbv2.model._`

The use of `getBOOL` was added just to your fork by the following commit:
`SHA ba435078
by janlisse, 04/12/2015 21:05
parent 53eb5522`

Though it only deals with the reading of bools not the writing of them (which is what caught my attention originally).

**Comment by glidester** [comment]
https://github.com/dwhjames/aws-wrap/pull/59 (ignore, wrong base repo)

**Comment by glidester** [comment]
https://github.com/mingchuno/aws-wrap/pull/11
